export const gradesInitialValues = {
        grades: [
            {
                aspek_penilaian_1: '',
                aspek_penilaian_2: '',
                aspek_penilaian_3: '',
                aspek_penilaian_4: '',
                name: 'mahasiswa_1',
            },
            {
                aspek_penilaian_1: '',
                aspek_penilaian_2: '',
                aspek_penilaian_3: '',
                aspek_penilaian_4: '',
                name: 'mahasiswa_2',
            },
            {
                aspek_penilaian_1: '',
                aspek_penilaian_2: '',
                aspek_penilaian_3: '',
                aspek_penilaian_4: '',
                name: 'mahasiswa_3',
            },
            {
                aspek_penilaian_1: '',
                aspek_penilaian_2: '',
                aspek_penilaian_3: '',
                aspek_penilaian_4: '',
                name: 'mahasiswa_4',
            },
            {
                aspek_penilaian_1: '',
                aspek_penilaian_2: '',
                aspek_penilaian_3: '',
                aspek_penilaian_4: '',
                name: 'mahasiswa_5',
            },
            {
                aspek_penilaian_1: '',
                aspek_penilaian_2: '',
                aspek_penilaian_3: '',
                aspek_penilaian_4: '',
                name: 'mahasiswa_6',
            },
            {
                aspek_penilaian_1: '',
                aspek_penilaian_2: '',
                aspek_penilaian_3: '',
                aspek_penilaian_4: '',
                name: 'mahasiswa_7',
            },
            {
                aspek_penilaian_1: '',
                aspek_penilaian_2: '',
                aspek_penilaian_3: '',
                aspek_penilaian_4: '',
                name: 'mahasiswa_8',
            },
            {
                aspek_penilaian_1: '',
                aspek_penilaian_2: '',
                aspek_penilaian_3: '',
                aspek_penilaian_4: '',
                name: 'mahasiswa_9',
            },
            {
                aspek_penilaian_1: '',
                aspek_penilaian_2: '',
                aspek_penilaian_3: '',
                aspek_penilaian_4: '',
                name: 'mahasiswa_10',
            },
            {
                aspek_penilaian_1: '',
                aspek_penilaian_2: '',
                aspek_penilaian_3: '',
                aspek_penilaian_4: '',
                name: 'mahasiswa_11',
            },
        ],
    };